sudo: false
language: java

jdk:
  - openjdk12

install:
  - ./gradlew assemble -i

script:
  - ./gradlew check -i

after_failure:
  chmod +x $TRAVIS_BUILD_DIR/print_surefire_reports.sh; $TRAVIS_BUILD_DIR/print_surefire_reports.sh
