sudo: false
language: java

jdk:
  - oraclejdk9

install:
- ./gradlew assemble -x signArchives -i

script:
- ./gradlew check -x signArchives -i

after_failure:
  chmod +x $TRAVIS_BUILD_DIR/print_surefire_reports.sh; $TRAVIS_BUILD_DIR/print_surefire_reports.sh
